import Head from 'next/head'

export default function Home({data}) {

  const ip = async () => {
    const res = await fetch('https://pushbutton.vercel.app/api')
    //const res = await fetch('http://localhost:3000/api/ip')
    console.log(res)
    const data = await res
    console.log(data)
  }

  const hello = async () => {
  const res = await fetch('https://pushbutton.vercel.app/api/hello')
  //const res = await fetch('http://localhost:3000/api/hello')
  console.log(res)
  const data = await res.json()
  console.log(data)
}

  const vercel = async () => {
  const res = await fetch('https://pushbutton.vercel.app/api/vercel')
  //const res = await fetch('http://localhost:3000/api/vercel')
  console.log(res)
  const data = await res.json()
  console.log(data)
}
  const cow = async () => {
  const res = await fetch('https://pushbutton.vercel.app/api/cow')
  //const res = await fetch('http://localhost:3000/api/vercel')
  console.log(res)
  const data = await res.json()
  console.log(data)
}

fetch('https://pushbutton.vercel.app/api')
.then(response => response.body)
.then(rb => {
  const reader = rb.getReader();

  return new ReadableStream({
    start(controller) {
      // The following function handles each data chunk
      function push() {
        // "done" is a Boolean and value a "Uint8Array"
        reader.read().then( ({done, value}) => {
          // If there is no more data to read
          if (done) {
            console.log('done', done);
            controller.close();
            return;
          }
          // Get the data and send it to the browser via the controller
          controller.enqueue(value);
          // Check chunks by logging to the console
          console.log(done, value);
          push();
        })
      }

      push();
    }
  });
})
.then(stream => {
  // Respond with our stream
  return new Response(stream, { headers: { "Content-Type": "text/html" } }).text();
})
.then(result => {
  // Do things with result
  console.log("readable stream?");
  console.log(result);
});

  return (
    <>
      <Head>
        <title>Push Button</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div 
        className='bg-green-600 h-32 w-32 text-white m-8'
        onClick={() => ip()}
      >
        IP
      </div>

      <div 
        className='bg-red-600 h-32 w-32 text-white m-8'
        onClick={() => hello()}
      >
        hello
      </div>

      <div 
        className='bg-blue-600 h-32 w-32 text-white m-8'
        onClick={() => vercel()}
      >
        vercel
      </div>

      <div 
        className='bg-yellow-600 h-32 w-32 text-white m-8'
        onClick={() => cow()}
      >
        cow
      </div>

    </>
  )
}

// export async function getServerSideProps(){
//   const res = await fetch('https://pushbutton.vercel.app/api/hello')
//   //const res = await fetch('http://localhost:3000/api/hello')
//   //const data = await res.json()
//   const data = await res.json()

//   return {props: {data}}
// }